// File generated by the FlutterFire CLI.
// DO NOT EDIT. This file is intended to be checked into version control and should not be manually edited.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1L3xJIypZ1vU5z3lEiXj0LMOs8mOu6uQ',
    appId: '1:819096727879:web:1234567890abcdef',
    messagingSenderId: '819096727879',
    projectId: 'humsafar-eb7f9',
    authDomain: 'humsafar-eb7f9.firebaseapp.com',
    storageBucket: 'humsafar-eb7f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1L3xJIypZ1vU5z3lEiXj0LMOs8mOu6uQ',
    appId: '1:819096727879:android:1234567890abcdef',
    messagingSenderId: '819096727879',
    projectId: 'humsafar-eb7f9',
    storageBucket: 'humsafar-eb7f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1L3xJIypZ1vU5z3lEiXj0LMOs8mOu6uQ',
    appId: '1:819096727879:ios:fe6c6546d7eb2be1f9dc62',
    messagingSenderId: '819096727879',
    projectId: 'humsafar-eb7f9',
    storageBucket: 'humsafar-eb7f9.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1L3xJIypZ1vU5z3lEiXj0LMOs8mOu6uQ',
    appId: '1:819096727879:macos:1234567890abcdef',
    messagingSenderId: '819096727879',
    projectId: 'humsafar-eb7f9',
    storageBucket: 'humsafar-eb7f9.firebasestorage.app',
  );
}
